### ISSUE TITLE
typeahead component

### ISSUE THREAD

**Issue by yayitswei** [Day8/re-com#10]
Thanks for making re-com!

A typeahead component would be great. Or, would it be appropriate to construct one from the dropdown-with-keyboard-support component?

**Comment by mike-thompson-day8** [comment]
We have no current plans for a typeahead component ourselves. Dropdown might be a good base. But happy to take patches.

**Comment by mike-thompson-day8** [comment]
I'm going to close this.  As noted, PRs for new components will be enthusiastically considered for inclusion.
