### ISSUE TITLE
Max choices in single-dropdown?

### ISSUE THREAD

**Issue by metasoarous** [day8/re-com#102]
This may be out of scope, but I would find it _extremely_ helpful to be able to specify an option like `:max-choices <int>` which would limit the number of options displayed. Combined with the `:filter-box? true` setting, this would make it possible to work with large choice collections, without blowing up on render. I'm happy to PR if this is something you think is in scope.

**Comment by Gregg8** [comment]
Yeah, would be happy to receive a PR for this. Thanks.

**Comment by superstructor** [comment]
As per discussion on #143 "a dropdown with hidden extra choices has poor usability, as there is no way to easily discover the extra options." 

So closing.
