### ISSUE TITLE
Default input on-change handler for atom models

### ISSUE THREAD

**Issue by shader** [Day8/re-com#104]
It would be super convenient if the on-change handler for input-text, etc. defaulted to `#(reset! model %)` whenever model is an atom.

Admittedly there will be many cases where that is not the desired action, but it seems like a reasonable default that can be easily overridden.

**Comment by Gregg8** [comment]
re-com is often used within re-frame which will be providing subscriptions rather than ratoms, so this default could lead to errors which are difficult to understand. Our philosophy is that it's better to be specific in this case.

**Comment by Gregg8** [comment]
Closing
