### ISSUE TITLE
Dropdown filtering messed up when using custom markup

### ISSUE THREAD

**Issue by juanedi** [Day8/re-com#107]
The filtering for dropdowns is currently being applied to the stringified result of `label-fn`. This is inconvenient since text for custom html markup tags will be considered. This means typing things like "div" can cause all options to pass the filter.

We should probably separate the logical label from the html used for rendering.

**Comment by juanedi** [comment]
Submitted pull request that adds a `render-fn` attribute, which produces the HTML for choices in the dropdown but is not taken into account for filtering.

**Comment by Gregg8** [comment]
Resolved by #108.
