### ISSUE TITLE
Multi-Select + Autocomplete

### ISSUE THREAD

**Issue by Conaws** [day8/re-com#115]
I know you already have a component for typeahead, and for selection, but I found I needed to combine the two, so I built a component that mixes both to create a sort of "Tag" interface.

![tags](https://cloud.githubusercontent.com/assets/2712495/19764489/d1d87c4e-9c60-11e6-801e-17f9fbb9edfe.gif)

If you'd accept a PR, I can convert into re-com style hoc

https://gist.github.com/Conaws/0c191c29f9e9f3781efa4b3535d28e7f # # #

**Comment by mike-thompson-day8** [comment]
Looks terrific.  We'd love a PR

**Comment by Frozenlock** [comment]
@Conaws any update on this?

**Comment by Conaws** [comment]
I had some trouble getting figwheel running on the latest master branch -- so hesitant to push a pr, but I updated the gist and added all the relevant css classes, so if you're cool passing in an option map rather than using the re-com style options you can copy the code from here

https://gist.github.com/Conaws/0c191c29f9e9f3781efa4b3535d28e7f

**Comment by superstructor** [comment]
As of `2.12.0` both a `multi-select` and `tag-dropdown` component have been added, which while not identical to the above example I believe should cover all the same use cases.
