### ISSUE TITLE
:width attribute on tabs components

### ISSUE THREAD

**Issue by stumitchell** [Day8/re-com#12]
Can you add this pretty please
Though it does work if I put it in the :style map

Stu

**Comment by Gregg8** [comment]
Since you asked so nicely, and since it looks like there are use cases to justify this, we'll include it in the next release.

**Comment by mike-thompson-day8** [comment]
See my concerns here:  https://github.com/Day8/re-com/issues/25#issuecomment-108678048

**Comment by stumitchell** [comment]
yeah Im not using it anyway
