### ISSUE TITLE
Single-dropdown: When you select an option, after the dropdown is hidden, if there is text under the cursor, text is selected up to the cursor.

### ISSUE THREAD

**Issue by UrKr** [Day8/re-com#124]
EDIT:
It seems that the text is selected from from somewhere to the cursor position at click 

The single dropdown selects/highlights (not sure what you call it) some text around the widget when a choice in the dropdown is clicked.

Likes so:

http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/dropdown

![image](https://cloud.githubusercontent.com/assets/7669179/20877911/0ab8b7fc-bacc-11e6-83b2-8391cdf7de9e.png)

Then, when I select a different choice ('Dropdown with grouping') some text bellow the text gets selected.

![image](https://cloud.githubusercontent.com/assets/7669179/20877933/21c5f608-bacc-11e6-97f1-73c0127158f8.png)

**Comment by UrKr** [comment]
I was able to reproduce it multiple times yesterday, but can't today.

**Comment by Gregg8** [comment]
I couldn't get it to selected text from just clicking an option

However, if you click the option, keep the mouse down and start moving, it will select, although I think you were experiencing this without all these extras.

Closing for now, but if you can demonstrate how to reproduce, we'll be happy to look into it.
