### ISSUE TITLE
Exception when providing nil model for datepicker

### ISSUE THREAD

**Issue by p-himik** [Day8/re-com#125]
I see `Error: No protocol method DateTimeProtocol.first-day-of-the-month- defined for type string` when providing a nil model for a datepicker. Apparently it was broken by 7b1cca6d9c8dd891299c49176f1154a4761d8a43 because empty string are `true` in ClojureScript and `first-day-of-the-month` doesn't like strings.

**Comment by Gregg8** [comment]
Fixed by #136
