### ISSUE TITLE
Eventually remove bug warning in h-box demo

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-com#14]
When Chrome 45 becomes stable (Aug 2015?), remove this warning in the `h-box` demo:
```There is a bug in Chrome. When switching from :between to :around (or visa versa), the change is not shown. To get around this, select a different value beforehand.```

Chrome 45 contains a fix for the bug. It might even be in Chrome 44.

**Comment by mike-thompson-day8** [comment]
Chrome Stable is currently still at 43 and it is mid July, so 45 will be more like September.

**Comment by Gregg8** [comment]
Fixed in Stable version 44. Can be removed now.

**Comment by Gregg8** [comment]
Done.
