### ISSUE TITLE
Typeahead doesn't close when clicking outside

### ISSUE THREAD

**Issue by nidu** [Day8/re-com#141]
In [this demo](http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/typeahead) typeahead doesn't close when clicking outside of it. This behaviour sounds intuitive after using most dropdown components. See also  [this comment](https://github.com/Day8/re-com/issues/130#issuecomment-277385969).

**Comment by Gregg8** [comment]
Fixed in #168. Available in re-com 2.2.0.
Closing.
