### ISSUE TITLE
popover should support a non atom showing?

### ISSUE THREAD

**Issue by stumitchell** [day8/re-com#148]
currently popover-anchor-wrapper and popover-content-wrapper will generate an error if `showing?` is a value not an atom.

This code should be changed to allow a simple boolean value.

Stu

**Comment by Gregg8** [comment]
Would be happy to accept a PR for this ;-)

**Comment by stumitchell** [comment]
https://github.com/Day8/re-com/pull/153

**Comment by superstructor** [comment]
Fixed in 00e8645 as a result of #153
