### ISSUE TITLE
support optional :id-fn in selection-list like in dropdown

### ISSUE THREAD

**Issue by hipitihop** [Day8/re-com#15]
**selection-list** assumes that elements in the set passed as `:model` are a sub-set of `:choices` and subsequently uses plain set as fn in [as-checked](https://github.com/Day8/re-com/blob/develop/src/re_com/selection_list.cljs#L34) and a similar direct match in [as-radio](https://github.com/Day8/re-com/blob/develop/src/re_com/selection_list.cljs#L54-L55).

- Add new optional arg `:id-fn` like [dropdown](https://github.com/Day8/re-com/blob/develop/src/re_com/dropdown.cljs#L203) It's default should be `:id` This will likely be a breaking change for existing consumers as they will need to specify `identity` to match current behaviour. Pass this through to `as-checked` `as-radio` and `:item-renderer` calls and use accordingly.
- change `*-clicked` `:on-change` handlers so that they are passed corresponding selections as expected. i.e. e.g if :id-fn = :id then :on-change is given set of :id values from :choices Consumers will need to take this into consideration in their :on-change if they want to deal with original :choices elements.

**Comment by mike-thompson-day8** [comment]
This component is marked as "Alpha".  I'm hoping this API change won't hurt anyone?

**Comment by mike-thompson-day8** [comment]
Fixed by 7ca70c01f55221008072f390fffd53338cfde30a
