### ISSUE TITLE
Multi-select dropdown

### ISSUE THREAD

**Issue by nikolap** [day8/re-com#150]
In addition to the single-dropdown component, it would be great to have a multi-dropdown component à la the multiple select dropdown from the [Bootstrap + Chosen demo](http://alxlit.name/bootstrap-chosen/).

I've made a [first pass attempt at this](https://github.com/nikolap/re-com) but need some feedback.

A critical decision made there is to unify `single-dropdown` and `multi-dropdown` into a generic `dropdown` function. There remains a deprecated `single-dropdown` function accessible in the `re-com.dropdown` namespace for existing projects, and is referred to in `re-com.core`.

I also attempted to maximize code reuse by integrating new features required for multi selection into existing `dropdown-top`, and `choice-item`.

The cost to doing this is that some args to dropdown become unusable in variations of dropdown. This includes:

- `filter-box?`: this is always on when `multi?` is true
- `title?`: does nothing currently when `multi?` is true. Perhaps can be a joined string of all the labels of selected items? Though this seems kind of strange when you have multiple items

Before I go any further down the rabbit hole (polishing, styling, etc.), feedback would be appreciated on whether unification into a generic `dropdown` function is a good approach or whether they should be kept as separate components. Also, of course, any thoughts or concerns on the changes made.

**Comment by Gregg8** [comment]
Thanks! Have had a play with this and we'd considered doing a multi-version in the past but never got around to it.

What you have there in terms of naming is fine. `dropdown` makes sense and having `single-dropdown` there for backward compatibility is right.

Comments (I know you said you're not done so you no doubt know about these):
 - Issue: As you select items, various errors and warnings appear in the console.
 - Issue: The "Choose a country" messages has no padding.
 - Suggestion: If you type a partial name and just press Enter, perhaps it should select the first result from the filtered list.

**Comment by Gregg8** [comment]
Also, please note that the `single-dropdown` component code has changed for the soon-to-be-released re-com version so you'll likely need to address some conflicts :-(

**Comment by nikolap** [comment]
Appreciate the feedback! No worries about the conflicts, I can merge them in.

I'll work cleaning this up and be back with a PR shortly when it's up to snuff.

**Comment by superstructor** [comment]
See #224
