### ISSUE TITLE
async dep broken in newer Clojure alphas

### ISSUE THREAD

**Issue by deg** [day8/re-com#154]
I just added re-com into a new Luminus-based project, where I had updated dependencies including to Clojure 1.9. Re-com broke my build, and the stack trace was awkward enough to make me head-scratch for too many minutes.

The problem was that the version of core.async included in re-com does not work in Clojure 1.9 Alpha15 or later.

I fixed in my project with an explicit include of core.async 0.3.443.  I've not tested enough to know if re-com can safely upgrade its dependency. Great if it can. If not, please add a warning to the readme.

**Comment by awb99** [comment]
core.async dependency in re-com also makes it impossible to use re-com in self-hosted clojurescript.

**Comment by BHConsulting** [comment]
Unsubscribe

**Comment by superstructor** [comment]
Has been upgraded to `1.3.610`.
