### ISSUE TITLE
Swinging needle meter

### ISSUE THREAD

**Issue by simon-brooke** [day8/re-com#157]
You folk might be interested in [this](https://github.com/simon-brooke/swinging-needle-meter) if only because imitation is the sincerest form of flattery. It represents two things:

1. I think it's a genuinely useful component in itself, and
2. It demonstrates generating dynamic SVG from re-com.

Let me know if you'd like me to work it up into an actual pull request.

**Comment by mike-thompson-day8** [comment]
Apologies for the very, very, very late response.  Thank you for the offer, but we'll be sticking with fairly stock standard UI widgets and leaving dashboard kinda stuff to other libraries.
