### ISSUE TITLE
Datepicker :enabled-fn instead of :enabled-days

### ISSUE THREAD

**Issue by ducky427** [Day8/re-com#16]
Currently the datepicker decides to enable/disable a date based on the day of the week and the user can decide select which days to enable/disable.

Is it possible to pass a function to the datepicker which decides whether to enable or disable a date? This would allow for fine grain support of this feature.

Thanks

**Comment by Gregg8** [comment]
Sounds like a useful idea for some quite specific situations. All our uses cases are fulfilled by `minimum`, `maximum` and `:enabled-days` so if we were going to add this, it would be down the track some time.

We'll leave it open in case anyone wants to have a go.

**Comment by mike-thompson-day8** [comment]
If anyone did want to have a go at a PR, then I'd suggest we make this a breaking API change in which `:enabled-days` is replaced by a new :selectable-date?` fn.  

I.e. I'm not keen on the idea of keeping `:enabled-days` if we have an additional way of determining selectable dates.

And take into account:  https://github.com/Day8/re-com/pull/9

**Comment by hipitihop** [comment]
Implemented [see commit](https://github.com/Day8/re-com/commit/ab883d91819559b8177cabdd35730b4cb2f02e15) Please note this is a breaking change removing parameter `:enabled-days` and introducing `:selectable-fn` a pred which is given a date as arg. This will be included in future release. Closing.

**Comment by ducky427** [comment]
Thank you!
