### ISSUE TITLE
ctrl-a (select all) not working for input-text in Firefox

### ISSUE THREAD

**Issue by Frozenlock** [Day8/re-com#17]
Tested with Firefox 38 on Ubuntu 14.04
Working (or rather not working) example:
http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/input-text

Type something into the `input-text` field and try to select all with `ctrl-a`.

**Comment by Gregg8** [comment]
Just tried that on my Windows Firefox and it worked fine. Then noticed I was on 37.0.2 and updated to 38.0.1 and it still worked. So I am thinking this is a Linux specific issue. 

I presume Ctrl+A works with other web pages containing text boxes.

Out of interest, does it work with other reagent apps with text boxes?

I also presume it's fine under Chrome Linux.

Not sure what we can do about this one if it's isolated to Firefox Linux.

**Comment by Frozenlock** [comment]
> Out of interest, does it work with other reagent apps with text boxes?

It does.

> I also presume it's fine under Chrome Linux.
Correct.

I think I found the problem:
`-moz-user-select: none;` seems to disable selection even in input fields.
I suppose the solution would be to remove (or override) this class for the input elements.

**Comment by Gregg8** [comment]
I can't confirm this myself, so could you please remove the "noselect" from this line:

https://github.com/Day8/re-com/blob/master/src/re_com/misc.cljs#L73

and let me know if that resolves the issue? Thanks.

**Comment by Frozenlock** [comment]
Yup, works like a charm.

**Comment by mike-thompson-day8** [comment]
Change made
