### ISSUE TITLE
Fix demo h-box rendering

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-com#176]
<img width="683" alt="screenshot of google chrome 6-04-18 5-14-18 pm" src="https://user-images.githubusercontent.com/811954/38404415-05e3e072-39be-11e8-98da-f10e9d54482e.png">

Click ":justify", and you see above^^.

**Comment by Gregg8** [comment]
Bootstrap CSS and some fonts are not loading because:
```Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.```

**Comment by mike-thompson-day8** [comment]
Because we are now loading via https:  https://re-com.day8.com.au

**Comment by danielcompton** [comment]
Fixed
