### ISSUE TITLE
h-split/v-split jump around when used inside an element with `position: relative`

### ISSUE THREAD

**Issue by p-himik** [day8/re-com#181]
`h-split` and `v-split` rely on `offsetLeft` and `offsetTop`, but these properties are calculated relative to the `offsetParent`, which is a closes positioned element. And the splits also use `clientX` and `clientY`, which are calculated within the viewport.
So, if the viewport does not coincide with the closest positioned element, a split's handler will jump on the first mouse move.

**Comment by Frozenlock** [comment]
Can confirm, bumped my head into the same issue.

**Comment by MawiraIke** [comment]
I have been able to reproduce this issue and fix it. I have changed the position calculation to be determined by using `pageXOffset`, `pageYOffset` and `getBoundingClientRect` which fix the issue. Thank you for spotting this.
