### ISSUE TITLE
Tabs and :class

### ISSUE THREAD

**Issue by Dangercoder** [Day8/re-com#184]
Hello,

Been using re-com for quite a lot of things on my website. Great stuff.

Having some issues with the "tabs"-component. the :class field is not working for me, it gives me an error in console.

```clojure
(defn tabs
  []
  (let [selected-tab-id (reagent/atom (:id (first tabs-definition)))     ;; holds the id of the selected tab
        change-tab      #(reset! selected-tab-id %)
        fn-name-width   "240px"]
    [re-com/horizontal-tabs
     :model     selected-tab-id
     :tabs      tabs-definition
     :class "overview-tab"
     :on-change change-tab]))
```

validate.cljs?rel=1529844148409:22 Invalid argument(s): (:class)

Not really sure what im doing wrong..

**Comment by Gregg8** [comment]
There's nothing wrong with that syntax. Are you sure the message is referring to this component? My gut feeling is that it's not.

**Comment by Dangercoder** [comment]
Hello Gregg8, I made some further research and I came this conclusion:
The problem was not the component. The problem was me not passing along a parameter when I was rendering the tabs there was an issue in re-frame/reagent.

**Comment by Dangercoder** [comment]
This is the code it's trying to run in my browser (Chrome), It's wierd because the class and attr parameters are missing. (From all methods in tabs.cljs)
```clojurescript
(defn horizontal-tabs
  [& {:keys [model tabs on-change id-fn label-fn style]
      :or   {id-fn :id label-fn :label}
      :as   args}]
  {:pre [(validate-args-macro tabs-args-desc args "tabs")]}
  (let [current  (deref-or-value model)
        tabs     (deref-or-value tabs)
        _        (assert (not-empty (filter #(= current (id-fn %)) tabs)) "model not found in tabs vector")]
    [:ul
     {:class "rc-tabs nav nav-tabs noselect"
      :style (flex-child-style "none")}
     (for [t tabs]
       (let [id        (id-fn  t)
             label     (label-fn  t)
             selected? (= id current)]                   ;; must use current instead of @model to avoid reagent warnings
         [:li
          {:class (if selected? "active")
           :key   (str id)}
          [:a
           {:style    (merge {:cursor "pointer"}
                             style)
            :on-click (when on-change (handler-fn (on-change id)))}
           label]]))]))
```

**Comment by Gregg8** [comment]
Well that explains it. Version 2.1.0 didn't support `:class`...

https://github.com/Day8/re-com/blob/2.1.0/src/re_com/tabs.cljs#L18

but latest does...

https://github.com/Day8/re-com/blob/master/src/re_com/tabs.cljs#L18-L20
