### ISSUE TITLE
Allow :ref as a component attribute

### ISSUE THREAD

**Issue by kaosko** [day8/re-com#185]
Current reagent allows :ref attribute for referring to the component itself at render time. For re-com components, using :attr {:ref #my-function} works but it's flagged as a warning:
"Validation failed for argument ':attr' in component ...". Would certainly be easy to add :ref to the attribute validation, but perhaps :ref should be supported as a first-class attribute across any re-com component?

**Comment by Frozenlock** [comment]
For the validation, I propose to add a section `react` with those 2 keys:
- `:ref`
- `:key`

( https://github.com/day8/re-com/blob/master/src/re_com/validate.cljs#L181)
