### ISSUE TITLE
TAB misbehaves with typeahead

### ISSUE THREAD

**Issue by mpisanko** [Day8/re-com#190]
With default settings on demo page (typeahead) when you input text 'aaa' - and press `<TAB>` - gets you `Error: No protocol method IAssociative.-assoc defined for type string: aaa`
This does not happen when you click out.

When :change-on-blur? is set to false - input value 'aaa', press `<TAB>`:
`Error rendering component (in Ky > UF >  >  > rA >  > Z >  > oA >  > reagent3 > xL > Z >  > lA >  > Z >  > lA >  > Z >  > cD)`
`TypeError: Cannot read property 'j' of null`

**Comment by Gregg8** [comment]
Fixed by #194

**Comment by mpisanko** [comment]
cheers!
