### ISSUE TITLE
Modal-panel incompatible with font-awesome

### ISSUE THREAD

**Issue by Frozenlock** [Day8/re-com#20]
I know `re-com` uses the material icons, but I'll let you know anyways...

Font-Awesome icons will appear on top of the modal (both the panel and the backdrop) *when they come AFTER the modal on the PAGE*.

See how every FA icon below the red line appears on top:
![image](https://cloud.githubusercontent.com/assets/1152041/7900015/3906c79e-070d-11e5-9845-54ea3ee315fb.png)

Everything works fine with the material icons, which is weird considering how similar they are. Both uses the `:before` pseudo-element.

-----
Here's the FA `i.fa.fa-list` replaced by the material `i.md.md-list`:

![image](https://cloud.githubusercontent.com/assets/1152041/7900041/af52b2a4-070e-11e5-8e47-c8bfa367f11f.png)

Works as expected.

**Comment by Gregg8** [comment]
The only thing I can think of without really looking into it is perhaps in the Font-Awesome CSS, they have a higher `z-index` value? We use 1020 for our modal component.

**Comment by Frozenlock** [comment]
That's what I first thought as well, but grepping the resource directory for z-index didn't return anything for font-awesome.  :-/

**Comment by Frozenlock** [comment]
Fixed by #24

**Comment by mike-thompson-day8** [comment]
@Frozenlock Thanks for the reports **and** fixes. Gregg has to finish off another small project before he can cycle back to re-com and push a new release.  Should be early next week.  Thanks again.
