### ISSUE TITLE
row-buttons tooltip incompatible with... er... rows (table).

### ISSUE THREAD

**Issue by Frozenlock** [Day8/re-com#21]
(I apologize for opening all these issues... I'm converting a project to this awesome library and discovering a few corner cases.)

The `row-button` doesn't work very well in a table.
The tooltip is truncated by the top and bottom rows, as well as the left and right cell.

![image](https://cloud.githubusercontent.com/assets/1152041/7900219/dcdafcd8-0716-11e5-9dfc-ee3e82b0e9a9.png)

**Comment by Gregg8** [comment]
Not sure if this will help, but we designed the component with a view to working within div-based layouts and as you have found, never tested these within html tables. We even added a few styles in re-com.css to assist here (rc-div-table, rc-div-table-header etc.).

Although we want to get a release out soon with some of these issues and PR's, we currently have limited time available now so probably won't be able to get to this one for this release.

My one thought for you is to try setting the `:no-clip?` arg in the popover/tooltip component as that prevents clipping in divs with scroll bars, which is not really the same situation as you're in but it's worth a try. Do you have an `:overflow` styling in any of your table markup? If so, try taking it out.

**Comment by Frozenlock** [comment]
Sounds like Re-com isn't made for tables.
I'll close this for now.
