### ISSUE TITLE
datepicker-dropdown cannot be styled. Existing :class and :attr args are passed to dropped down datepicker

### ISSUE THREAD

**Issue by hipitihop** [day8/re-com#215]
The dropdown datepicker cannot be styled. The existing :class and :attr args are passed to the dropped down datepicker. In this example the `"foobar" class end up on the datepicker dv, not on the wrapper/label/activator.

```clojure
 [rc/datepicker-dropdown
   :class   "foobar"
   :model   my-date-model
   :format  date/wc-date-format
   :on-change  #(dispatch [::date-changed {:new-date %}])]
```

Perhaps we want to consider adding additional args to support styling and attributes for the wrapper.

Also see https://github.com/day8/re-com/issues/216

**Comment by superstructor** [comment]
This is fixed as of `2.12.0` or later with `:parts` arg. See https://re-com.day8.com.au/#/date
