### ISSUE TITLE
No `dev-auto` alias.

### ISSUE THREAD

**Issue by Honeypot95** [day8/re-com#220]
The README.md specifies that if one wants to try the demos, it should run the `dev-auto` alias:
```
lein dev-auto
```
but when I try the command, it fails with lein saying there is no such alias.
```
'dev-auto' is not a task. See 'lein help'.
```

I saw that there is a `ci` alias that came up with a google search of the issue, but if this replaced the `dev-auto` alias, then it seems to be doing much more.

I think at least the documentation has to change. In the meantime, what is the proper way of running the demos?

I tried this running ubuntu 20.10, with lein 2.9.1 and java 13.0.4, and also in a Dockerfile, with ubuntu 18.04, lein 2.8.1 Java 1.8.0_275

**Comment by superstructor** [comment]
Thanks for raising this issue @Honeypot95  👍 

Documentation was not updated to new aliases when we moved to shadow-cljs/lein-shadow.

`lein dev-auto` is now `lein watch` .
