### ISSUE TITLE
tag-dropdown silently hides options

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-com#230]
When too many choices are selected, and the component runs out of horizontal space, choices are silently dropped off which is a bad UX.  Here's a demonstration from the Demo app ... 

![image](https://user-images.githubusercontent.com/3033376/105620022-7f3a8880-5e4c-11eb-9814-71d82a4d69e6.png)

Solutions: 
1.  add a `...` at the end?  Perhaps more wordy `... 3 more` 
2.  cause the containing box to expand vertically to allow for another row of tags?
3.  let the component grow horizontally somehow?

What other solutions?

**Comment by mike-thompson-day8** [comment]
And it also hides the "ghost"

![image](https://user-images.githubusercontent.com/3033376/105621063-ce39eb00-5e57-11eb-97ba-633384d0244d.png)

**Comment by schpaa** [comment]
Other solution; perhaps a drop down indicator?

**Comment by mike-thompson-day8** [comment]
Where choice names collectively get too wide, we're going to make two strategies available to a programmer:
1.  allow the component to grow horizontally via their use of `:min-width` and `:max-width` args 
2.  A programmer can configure the component to "switch" to using "abbreviations" when "names" get too wide. Provide an `:abbrev-fn` and an `:abbrev-threshold` over which abbreviations should be used instead of name.

**Comment by superstructor** [comment]
Resolved with:
1. `:min-width` and `:max-width` arguments
2. `:abbrev-fn` and `:abbrev-threshold`

See above comment and documentation at https://re-com.day8.com.au/
