### ISSUE TITLE
Modify `tag_dropdown` Demo 

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-com#236]
![image](https://user-images.githubusercontent.com/3033376/105948606-52da7280-60bf-11eb-8328-dc06e4926e05.png)

**Comment by mike-thompson-day8** [comment]
![image](https://user-images.githubusercontent.com/3033376/106133428-59e5ab80-61b9-11eb-80fc-3903719bc070.png)

**Comment by mike-thompson-day8** [comment]
Also, setting `:disabled?` was supposed to turn the input box grey, like a disabled InputText

**Comment by superstructor** [comment]
Resolved in 67d0eb2ec8417fa34751ac93694a40146b40c650 and e52be4354ff82a174f71cd878cc553f793034b5a
