### ISSUE TITLE
datepicker: issues with selectable-fn and getIsoWeekday following update to 2.12

### ISSUE THREAD

**Issue by alex314159** [day8/re-com#240]
Thanks again for the great project. Update went smoothly and is very useful, but I have this weird bug in datepicker:

```
[datepicker-dropdown :model entry-date :selectable-fn #(< (.getIsoWeekday %) 5)] ;only select weekdays
```

The above worked in the previous version, but now I get `Cannot infer target type in expression (. p1__57909# getIsoWeekday)?`. What's also strange is that some other goog.time functions such as `.getDay` work. I've also tried to type hint to `^DateTime` but without success.

Thanks for the help,

**Comment by superstructor** [comment]
I can't answer as to why the behavior changed, maybe you have also upgraded your compiler (shadow-cljs?) at the same time. 

I did reproduce the above compiler warning, and fixed it with either of the following both working:
```clojure
#(< (.getIsoWeekday ^js %) 5)
```clojure
or
```clojure
#(< (.getIsoWeekday ^js/DateTime %) 5)
```

**Comment by alex314159** [comment]
you're right I had updated shadow-cljs, too! Thanks for the tip that worked!
