### ISSUE TITLE
tag_dropdown  confusion

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-com#241]
I just updated some of the docs for `tag_dropdown` and, in the process, I realised I really wasn't clear on `:min-width` and `:max-width`.  And the existing Demo was not flexible enough to allow me to experiment and answer my own questions. 

Observations:
1.  Should `:min-width` just be called `:width` ??   I believe it represents the "natural width" the programmer chooses.  
2.  What happens if no `:min-width` is supplied.  What is the "natural width"?  I couldn't check this because the demo doesn't have a tickbox for `:min-width`.  Assuming this parameter remains optional, it probably should have a tickbox, so you can see what happens. 
3.  If no `:max-width` is supplied what happens?  Again, I couldn't check this via demo because of no tickbox. I kinda assume the "it-automatically-grows-to-this-size" feature would be turned off.  But then I realised that there was another interpretation: perhaps it means that horizontal-growing-thing is turned off?  Need to decide which and document.

**_Note_**: I left behind some `XXX` in the BOTH the Docs page and the Parameters definitions.  Once the issues above are decided, please correct them.

**Comment by superstructor** [comment]
Resolved with demo of turning  on/off min-width and max-width. Still need to resolve the documentation XXX.
