### ISSUE TITLE
Suggested changes to simple-v-table demo 

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-com#242]
![image](https://user-images.githubusercontent.com/3033376/106067588-22441880-6153-11eb-9ff0-ab775df1bec7.png)

**Comment by mike-thompson-day8** [comment]
Also: 
1. Add a "units" column to the right of existing. just to get more width, to make the scrollbar operation more interesting. 
2.  When `:max-rows` is turned off the table will expand vertically as far as it can.  So you might need to set container height. Maybe.

**Comment by Gregg8** [comment]
Add more padding between the elements (and more vertical spacing?)

![image](https://user-images.githubusercontent.com/3037372/106068870-705a1b80-6155-11eb-9264-d475275c737d.png)

Also, add `:align-center` to those `h-box`es to improve their positioning

**Comment by Gregg8** [comment]
![image](https://user-images.githubusercontent.com/3037372/106070281-46562880-6158-11eb-8210-99c498470b36.png)
