### ISSUE TITLE
Does `v-table` need `:id-fn`  ?

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-com#243]
What purpose does `:id-fn` serve in `v-table`?  The component itself seems to work principally with `row-index` and the elements of `:model`

Can we remove it?  Should we change it?

Gregg's initial answer:
```
It's primary purpose is to provide a unique id for React, just like in any of our other 
re-com components that render lists of things.
Note that row-index was added later, so perhaps we can revisit using row-index as unique ids. 
I would have to look further into it
```

My guess is that we can probably move to `row_index`. That would make scrolling efficient (aka adding and removing rows). However in apps where the underlying `:model` is changing (items are being added and removed often), then letting the programmer control this would be a good idea.  Its just that this is an edge case I think.  

Proposal:
1.  Gregg checks if `:id-fn` is only used in this one way (for React keys). 
2.  If so, we keep `:id-fn` but we:
    - document that's the purpose and change the name to reflect its real purpose:  `:key-fn`
    - make it optional 
    - make it take two args `row_index` and `row` 
    - provide a default which returns the `row-index` arg

**Comment by Gregg8** [comment]
1. Yep, only used for React keys
2. Done (except the code determines if `:key-fn` needs to be called, so no need to pass it two args)
