### ISSUE TITLE
selection-list fires on-change when clicking on existing selection in single select mode

### ISSUE THREAD

**Issue by hipitihop** [day8/re-com#247]
When the selection-list is configured for single selection, if you click on the item which is already selected, the :on-change fires each time you click, even thought the :model is not changing. In the example below, if you click on item 1, the on-change fires.

![image](https://user-images.githubusercontent.com/4626024/106999239-8f018780-67d1-11eb-83ed-f5ec0e8cf983.png)

**Comment by superstructor** [comment]
Fixed in  5a9dd396e898ce1535fd2164cd7b6f18a79dd95e
