### ISSUE TITLE
Allow boxes (flex rows) to wrap

### ISSUE THREAD

**Issue by Frozenlock** [Day8/re-com#25]
I faced a situation where I wanted an horizontal row to wrap if the container was becoming too small.

A solution is to manually provide `:flex-flow "row wrap"` via the `:style`, but I think it would be cleaner (and more intuitive for the users) if a simple :`allow-wrap?` argument was present.

**Comment by Gregg8** [comment]
I do agree with you. We have never had that requirement but it is an important part of the flex box universe (and trivial to implement) so sure, will do.

**Comment by mike-thompson-day8** [comment]
I'm cautious about every additional named arg (on any component, not just this one).  We don't want perpetually expanding named args lists (and that's what will happen unless we are on our guard).

As frozenlock says `:style` is the easy escape hatch -- you can do anything there. Named args, on the other hand, are for what we see as THE most common usecases. 

For something to get "promoted" from `style` to a `named arg` it must be used in, what?, 50% of cases?  Dunno exactly what the criterial is, but you get the idea -- I'd like the bar to be high.

So, as a general rule, we should default to saying "no" to new named args, unless the case is strong. 

None of this is to say that, in this case, the answer is "no".  This is just me setting a mental framework.

**Comment by stumitchell** [comment]
so what do you think about passing all unused keyword args directly to :style?

**Comment by Frozenlock** [comment]
I often add `:on-click` to various components... I'd rather not having that sent into the style map.  :wink: 

Using `:style` is not so bad, but the thing that bugs me in this particular case is that the boxes are an almost complete abstraction. 

I can use them without knowing anything about flexbox.
The wrap issue was the first thing that really throw me off and forced me to check some documentation.

**Comment by Gregg8** [comment]
:facepunch:

**Comment by mike-thompson-day8** [comment]
@Frozenlock I'm pleasantly surprised - I thought the layout side of things was a fairly leaky abstraction over flexbox.  Damn useful, hopefully, but leaky.  Must be more watertight than I thought, which is good! 

So, it sounds like you wanted `:allow-wrap?` more for reasons of completeness, than grinding, constant hassle.

Next, I can straight-away imagine the need for `:on-click` in various places. Were there any components in particular?

(BTW, the "iron first of Gregg" mentions are a reference to Gregg's jack-booted ways when it comes to "tweaking" APIs and calmly ignoring the blood curdling screams of those affected.  For the greater good, he claims, but some wonder. So, an insiders joke, but now you know. Fear the fist)

**Comment by Frozenlock** [comment]
@mike-thompson-day8 

> So, it sounds like you wanted :allow-wrap? more for reasons of completeness, than grinding, constant hassle.

Correct. I only needed it once so far, and I've been pretty busy with `re-com`. :smile: 

I don't mind using `:attr` for the random `:on-click`. I don't think it occurs enough to warrant its own key. (Outside of buttons)

**Comment by mike-thompson-day8** [comment]
So, I think this can be closed without further action.
