### ISSUE TITLE
Port Scripts to Babashka

### ISSUE THREAD

**Issue by superstructor** [day8/re-com#277]
babashka 0.3.2 [has added rewrite-clj](https://github.com/babashka/babashka/issues/769).

Please replace `lein exec` w/ Babashka-only implementation.

- How to run tests w/ babashka ? I imagine run a "test script" that depends on the normal script.
- Update README and docs w/ instructions pointing to installation instructions for Babashka, and how to run the script and tests w/ Babashka.

**Comment by mike-thompson-day8** [comment]
Here's a sample `bb` script:
https://gist.github.com/laurio/01530ea7700752885df21e92bb926f75
