### ISSUE TITLE
Side panel navbar

### ISSUE THREAD

**Issue by rej156** [Day8/re-com#28]
Was curious if this could be implemented or how for that matter in re-com or reagent.

**Comment by Gregg8** [comment]
We don't have a side panel navbar as a part of the re-com library. The closest thing is `vertical-bar-tabs`: file:///D:/dev/Day8/ClojureScript/reagent-components/run/resources/public/index_prod.html#/tabs

We did however, implement one in the re-com demo: https://github.com/Day8/re-com/blob/master/src/re_demo/core.cljs#L103-L138

Feel free to use that code as a basis for what you want.
