### ISSUE TITLE
Example of a re-com form with re-frame's dispatch

### ISSUE THREAD

**Issue by yayitswei** [Day8/re-com#30]
Could you provide an example of hooking up a re-com element to re-frame's app-db?

My attempt required some unexpected hacks:

```Clojure
(def path [:my-form])
(def path-m (re-frame.core/path path))

(register-handler
  ::input-changed
  [debug path-m]
  (fn [db' [_ k value]]
    (assoc db' k value)))

(register-sub
 ::input
  (fn [db [_ k]]
    (reaction (get-in @db (conj path k)))))

(defn address-input []
  (let [address (subscribe [::input :address])])]
    (fn []
       [rc/input-text
       :model (or @address "")
       :on-change #(dispatch [::input-changed :address %])])))
```

In particular, without the `(or @address "")`, I get an error on the initial page load: `Validation failed for argument ':model' in component 'input-text': Expected 'string | atom'. Got 'nil'`

**Comment by mike-thompson-day8** [comment]
The code looks about right.  Although your `assoc` and `get-in` seem to work on different paths. 

BTW, if you are going to be using `on-change`  to get character by character updates  (rather than `on-blur`) then make sure you use `dispatch-sync`, not `dispatch` (or you stand the chance of dropping chars).  See #39.

**Comment by yayitswei** [comment]
Good to know about `dispatch-sync`.

I put together a few helper functions for wiring up form elements. The textbox model needs a dereference but the radio button doesn't.. I'll investigate more.

```Clojure
(defn wired-textbox [{:keys [label key]}]
  (let [model (subscribe [::input key])]
    (fn []
      [rc/v-box
       :children
       [[rc/label :label label]
        [rc/input-text
         :model (or @model "")
         :on-change #(dispatch [::input-changed key %])]]])))

(defn wired-radiogroup [{:keys [label key options]}]
  (let [model (subscribe [::input key])]
    (fn []
      [rc/v-box
       :children
       [[rc/label :label label]
        [rc/v-box
         :gap "10px"
         :children
         [(doall (for [[c label] options]
                   ^{:key c}
                   [rc/radio-button
                    :label label
                    :value c
                    :model model
                    :label-style (if (= c @model) {:font-weight "bold"})
                    :on-change #(dispatch [::input-changed key c])]))]]]])))
```

Btw, re-com is the best component library I've used so far. Thanks for releasing it! Hope to see more adoption.
