### ISSUE TITLE
Improve figwheel usage ?

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-com#31]
Perform the following experiment ... 

If we were to add
    `:figwheel {:on-jsload "re_demo.core/render-root”}` 
to `project.clj` for the `dev` build target, could we then remove the entire `dev` folder (which is only there for figwheel reloading purposes). 

And would this, in turn, mean we could collapse the two HTML files (one for prod and one for dev)? What other knock on effects?  

We'd need to check that the Google Closure compiler dead-code-eliminates all  figwheel artifacts from `prod` builds.  (Although it seems clear that this would happen correctly, let's check).

**Comment by Gregg8** [comment]
Implemented in [2b7eb66](https://github.com/Day8/re-com/commit/2b7eb66912f57fc65b6e97ae7b11942f33ae56a7)
