### ISSUE TITLE
Conflicting documentation in splits

### ISSUE THREAD

**Issue by MawiraIke** [day8/re-com#310]
In the documentation of [splits](https://re-com.day8.com.au/#/splits), the `parts` option is indicated to expect a `left` and `right` assignment in `h-split`. However, it seems to use the `top` and `bottom` assignments like `v-split` in the code. E.g. [for `h-split` `left`](https://github.com/Day8/re-com/blob/master/src/re_com/splits.cljs#L188). 
There is a comment in the code close by 
![msedge_3R4QihIolg](https://user-images.githubusercontent.com/38689046/147361330-223b2000-a835-4dc0-b115-c8b4b12562f8.png)

 Assuming this, should we change the documentation to `:top` and `:bottom` for `h-split`?

**Comment by superstructor** [comment]
Nope the comment would be in regards to the css class `rc-h-split-top` specifically.

left/right is the correct terminology for h-split in all cases.

top/bottom is the correct terminology for v-split in all cases.
