### ISSUE TITLE
recent changes to v-table still has rendering issues in 2.21.4

### ISSUE THREAD

**Issue by hipitihop** [day8/re-com#341]
e.g. this when in table mode in results for Curve8.

![image](https://github.com/day8/re-com/assets/4626024/d18ef774-47df-4087-b5c2-083915b326c1)

Reverting to v2.19.0 corrects the issue

**Comment by kimo-k** [comment]
Hey @hipitihop,

A while back, I changed the signature of `simple-v-table`'s` `:row-renderer` and `:column-header-render` functions. Should have known this might be a breaking change. Only `simple-v-table` is affected, not `v-table`.

When users pass in their own function for `:row-renderer` or `:column-header-render`, it needs to have the new signature: a single map of keyword arguments, not positional arguments.

The changes above should be all we need to fix prod.
