### ISSUE TITLE
component attribute tabIndex causes console validation warning

### ISSUE THREAD

**Issue by hipitihop** [day8/re-com#347]
If you set the `:attr` prop e.g. `:attr {:tabIndex -1}`. 
I haven't tested all re-com components to see if it only effects checkbox or all others.

```
validate.cljs:26 Validation failed for argument ':attr' in component 're_com.checkbox.checkbox': Unknown HTML attribute(s): (:tabIndex)
```

**Comment by kimo-k** [comment]
Our validator doesn't support react-style camel-cased props. `:tabIndex` fails, but `:tab-index` passes. I think this is by design. Maybe we could add a "did-you-mean..." remark to the warning in cases like this.

**Comment by hipitihop** [comment]
You are indeed correct. Maybe others get tripped up by this at times, so a "did-you-mean" might have some merit. But closing this for now. Thanks @kimo-k
