### ISSUE TITLE
Upgrade to Latest Version Of the Material Design Icon Font

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-com#36]
The icon font used by re-com http://zavoloklom.github.io/material-design-iconic-font/icons.html  has moved from v1 to v2.  

In the process the icons have changed name.  http://zavoloklom.github.io/material-design-iconic-font/v1/  What was `md-` has become `zmdi-`  so upgrading to v2 will be a breaking change.

**Comment by Gregg8** [comment]
Implemented in [8fb588a](https://github.com/Day8/re-com/commit/8fb588a29f2267abfc86aaa4fc09dac7f59b9791)
