### ISSUE TITLE
Split Component: Add on-drag-complete function to the API

### ISSUE THREAD

**Issue by ducky427** [Day8/re-com#4]
Hi,
I have a stateful reagent component as one the two panels in a `h-split`. When the splitter is dragged, I need to do some work to show the appropriate things [update some canvas updated animation].

Is it possible to pass an `on-drag-complete` function to a splitter? The default value could just be the identity function or you could check if the function if not nil and if so, call it.

It could possibly be called here: [L146](https://github.com/Day8/re-com/blob/master/src/re_com/splits.cljs#L146).

Thanks

**Comment by mike-thompson-day8** [comment]
Notes:
  - parameter would be optional
  - I'm tempted to call it `on-split-change`.  
  - it would be called with one, number parameter which is the new split-percentage
  - and yes, it would be called in `stop-drag`. 
 - change to be made to both v-split and h-split in the same way. 

If you agree, we'll put it in a release later today.

**Comment by ducky427** [comment]
That makes sense to me. :+1:

**Comment by ducky427** [comment]
Works in v0.5.0.

Thanks a lot!
