### ISSUE TITLE
Move secretary into dev dependencies

### ISSUE THREAD

**Issue by Frozenlock** [Day8/re-com#42]
`Re-com` allows any routing library to be used. (I, for example, am using [Bidi](https://github.com/juxt/bidi).)

One should not have to depend on `secretary` if it's not used in his project.

**Comment by mike-thompson-day8** [comment]
Sure, So you are just asking that `secretary` be moved to be a `dev` dependency.

**Comment by Frozenlock** [comment]
Correct. I was surprised when I saw it show up in my `lein deps :tree`.

I hope it won't cause too much delay for the next version. :smile:

**Comment by mike-thompson-day8** [comment]
I've estimated 2 days :-)  One day of which is testing.
