### ISSUE TITLE
input-text :on-key-up fn

### ISSUE THREAD

**Issue by pate** [Day8/re-com#43]
I need to validate input as it is typed and not just on-change (which is called on-blur), otherwise Aunt Marge thinks the serial number she just entered is invalid.

Please consider letting us override validation-fn with something other than a regex, or let us specify :on-key-up for keys that are not just 27 and 13. Thanks!

**Comment by mike-thompson-day8** [comment]
Set  `:change-on-blur` to `false`.
See demo and explanation:  http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/input-text

**Comment by freckletonj** [comment]
@mike-thompson-day8 This solution took me a couple hours to find. Specifically, I just wanted to create an input box that allows me to fire `re-frame/dispatch` on every `on-change`, but also to have an `:attr {on-key-up (fn [] ...` to fire a different `dispatch` when the user hits `<enter>`.

Also, it took me another chunk of time to find that `:attr` attribute for adding arbitrary attributes.

Just feedback, to make things more useful.

I super love `re-frame` and `re-com` by the way, thanks for the hard work!
