### ISSUE TITLE
Center Title Component

### ISSUE THREAD

**Issue by brandonparsons** [Day8/re-com#52]
Hi there - just starting to play around with `re-com`!

How can I go about centering a `re-com/title` component in the window? I've tried fiddling with an `h-box` but I'm new to flexbox as well :)

**Comment by Gregg8** [comment]
You actually want a `v-box` (to lay things down the page) and the magic is the `:align` argument...

```
[re-com/v-box
  :align :center
  :children [[re-com/title :level :level2 :label "Main Title"]
             [re-com/title :level :level3 :label "Sub-title"]]]
```

If you haven't already, check these links out in our demo. There a lot of good detail in there and some further links on Flexbox:

http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/introduction
http://re-demo.s3-website-ap-southeast-2.amazonaws.com/#/layout

(open again if you have further related questions)

**Comment by brandonparsons** [comment]
Thanks @Gregg8  - will try this tonight :)
