### ISSUE TITLE
Feature Request: (Datepicker) Allow first day of week as per ISO 8601 standard.

### ISSUE THREAD

**Issue by akaivola** [Day8/re-com#55]
Quote from Wikipedia:
"in some Muslim countries and Israel, Sunday is the first work day of the week. According to the Hebrew calendars and traditional Christian calendars, Sunday is the first day of the week and according to the International Organization for Standardization ISO 8601 Sunday is the seventh and last day of the week."

**Comment by mike-thompson-day8** [comment]
Happy to take a PR for this.  But not something that we'll implement ourselves in the near future.

**Comment by Gregg8** [comment]
Resolved by #89.
