### ISSUE TITLE
Does modal with for mobile device?

### ISSUE THREAD

**Issue by wqhhust** [Day8/re-com#56]
I have the following modal-panel
https://github.com/wqhhust/test_frame/blob/master/src/cljs/test_frame/views.cljs#L23

It works when browser it in PC, but not good in android. Does modal-panel support andiod?

**Comment by Frozenlock** [comment]
From the readme:

>  We can also confirm that none of the components have been designed with mobile in mind, and that there's no attempt to handle media queries. We said we had a desktop app focus, right?

**Comment by wqhhust** [comment]
sorry, miss that part of the readme. It's a great library, but a pity not support mobile.
