### ISSUE TITLE
single-dropdown does not accept lists

### ISSUE THREAD

**Issue by stumitchell** [Day8/re-com#58]
selection-lists can take an list as their :choices parameter
single-dropdowns fail with this error

`Validation failed for argument ':choices' in component 'single-dropdown': Expected 'vector of choices | atom'. Got '({:id :market, :label "Market", :category :member-set, :s...'re_com.validate.log_error.cljs$core$IFn$_invoke$arity$variadic @ validate.cljs:21re_com$validate$log_error @ validate.cljs:18re_com.validate.validate_fns_pass_QMARK_.validate_arg @ validate.cljs:90(anonymous function) @ core.cljs:4067cljs.core.map.cljs$core$IFn$_invoke$arity$2 @ core.cljs:4067(anonymous function) @ core.cljs:2863cljs.core.LazySeq.sval @ core.cljs:2863cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 @ core.cljs:2905cljs$core$seq @ core.cljs:943cljs.core.Cons.cljs$core$INext$_next$arity$1 @ core.cljs:2736cljs$core$next @ core.cljs:988cljs.core.LazySeq.cljs$core$INext$_next$arity$1 @ core.cljs:2888cljs$core$next @ core.cljs:988cljs$core$every_QMARK_ @ core.cljs:3606re_com$validate$validate_fns_pass_QMARK_ @ validate.cljs:79re_com.validate.validate_args.cljs$core$IFn$_invoke$arity$variadic @ validate.cljs:110re_com$validate$validate_args @ validate.cljs:97re_com.dropdown.single_dropdown.cljs$core$IFn$_invoke$arity$variadic @ dropdown.cljs:217re_com.dropdown.single_dropdown.cljs$lang$applyTo @ dropdown.cljs:210cljs.core.apply.cljs$core$IFn$_invoke$arity$2 @ core.cljs:3300cljs$core$apply @ core.cljs:3292(anonymous function) @ component.cljs:45reagent$impl$component$do_render @ component.cljs:45(anonymous function) @ component.cljs:64reagent$ratom$capture_derefed @ ratom.cljs:18reagent$impl$batching$run_reactively @ batching.cljs:95(anonymous function) @ component.cljs:64ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ react.inc.js:6975ReactCompositeComponentMixin._renderValidatedComponent @ react.inc.js:7002wrapper @ react.inc.js:13427ReactCompositeComponentMixin.mountComponent @ react.inc.js:6423wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactMultiChild.Mixin.mountChildren @ react.inc.js:12871ReactDOMComponent.Mixin._createContentMarkup @ react.inc.js:7737ReactDOMComponent.Mixin.mountComponent @ react.inc.js:7647ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactMultiChild.Mixin.mountChildren @ react.inc.js:12871ReactDOMComponent.Mixin._createContentMarkup @ react.inc.js:7737ReactDOMComponent.Mixin.mountComponent @ react.inc.js:7647ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactMultiChild.Mixin.mountChildren @ react.inc.js:12871ReactDOMComponent.Mixin._createContentMarkup @ react.inc.js:7737ReactDOMComponent.Mixin.mountComponent @ react.inc.js:7647ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactMultiChild.Mixin.mountChildren @ react.inc.js:12871ReactDOMComponent.Mixin._createContentMarkup @ react.inc.js:7737ReactDOMComponent.Mixin.mountComponent @ react.inc.js:7647ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactMultiChild.Mixin.mountChildren @ react.inc.js:12871ReactDOMComponent.Mixin._createContentMarkup @ react.inc.js:7737ReactDOMComponent.Mixin.mountComponent @ react.inc.js:7647ReactReconciler.mountComponent @ react.inc.js:14128ReactCompositeComponentMixin.mountComponent @ react.inc.js:6433wrapper @ react.inc.js:13427ReactReconciler.mountComponent @ react.inc.js:14128ReactMultiChild.Mixin._mountChildByNameAtIndex @ react.inc.js:13079ReactMultiChild.Mixin._updateChildren @ react.inc.js:12985ReactMultiChild.Mixin.updateChildren @ react.inc.js:12930ReactDOMComponent.Mixin._updateDOMChildren @ react.inc.js:7918ReactDOMComponent.Mixin.updateComponent @ react.inc.js:7767ReactDOMComponent.Mixin.receiveComponent @ react.inc.js:7751ReactReconciler.receiveComponent @ react.inc.js:14187ReactCompositeComponentMixin._updateRenderedComponent @ react.inc.js:6934ReactCompositeComponentMixin._performComponentUpdate @ react.inc.js:6912ReactCompositeComponentMixin.updateComponent @ react.inc.js:6828wrapper @ react.inc.js:13427ReactCompositeComponentMixin.receiveComponent @ react.inc.js:6692ReactReconciler.receiveComponent @ react.inc.js:14187ReactChildReconciler.updateChildren @ react.inc.js:4789ReactMultiChild.Mixin._updateChildren @ react.inc.js:12956ReactMultiChild.Mixin.updateChildren @ react.inc.js:12930ReactDOMComponent.Mixin._updateDOMChildren @ react.inc.js:7918ReactDOMComponent.Mixin.updateComponent @ react.inc.js:7767ReactDOMComponent.Mixin.receiveComponent @ react.inc.js:7751ReactReconciler.receiveComponent @ react.inc.js:14187ReactCompositeComponentMixin._updateRenderedComponent @ react.inc.js:6934ReactCompositeComponentMixin._performComponentUpdate @ react.inc.js:6912ReactCompositeComponentMixin.updateComponent @ react.inc.js:6828wrapper @ react.inc.js:13427ReactCompositeComponentMixin.receiveComponent @ react.inc.js:6692ReactReconciler.receiveComponent @ react.inc.js:14187ReactCompositeComponentMixin._updateRenderedComponent @ react.inc.js:6934ReactCompositeComponentMixin._performComponentUpdate @ react.inc.js:6912ReactCompositeComponentMixin.updateComponent @ react.inc.js:6828wrapper @ react.inc.js:13427ReactCompositeComponentMixin.performUpdateIfNecessary @ react.inc.js:6725ReactReconciler.performUpdateIfNecessary @ react.inc.js:14205runBatchedUpdates @ react.inc.js:14955Mixin.perform @ react.inc.js:16683Mixin.perform @ react.inc.js:16683assign.perform @ react.inc.js:14899flushBatchedUpdates @ react.inc.js:14979wrapper @ react.inc.js:13427Mixin.closeAll @ react.inc.js:16756Mixin.perform @ react.inc.js:16697ReactDefaultBatchingStrategy.batchedUpdates @ react.inc.js:9199enqueueUpdate @ react.inc.js:15019enqueueUpdate @ react.inc.js:14537ReactUpdateQueue.enqueueForceUpdate @ react.inc.js:14660ReactComponent.forceUpdate @ react.inc.js:6018reagent$impl$batching$run_queue @ batching.cljs:40reagent.impl.batching.RenderQueue.run_queue @ batching.cljs:63(anonymous function) @ batching.cljs:57
log_util.cljs:122 12:24:10.068  day8.base.util:282  "gzip name: events length: 65269"`

**Comment by Gregg8** [comment]
This has probably been updated since then, because we now use `sequential?` to validate the collection passed to both `single-dropdown` and `selection-list` and on testing just now, it allowed a list for both.

Closing, but reopen if I'm missing something.
