### ISSUE TITLE
Components in splitter panels not updating

### ISSUE THREAD

**Issue by ZTO** [Day8/re-com#59]
Components only seem to update when they deref a ratom, but not on changing arguments.

    (def cnt (r/atom 0))
    (defn myspan1 [] [:span @cnt])
    (defn myspan2 [t] [:span t])
    (defn demo []
      [:div
        [re-com/button :label (str "inc " @cnt) :on-click #(swap! cnt inc)]
        [re-com/h-split :panel-1 [:div "works: " [myspan1]]
                        :panel-2 [:div "doesn't: " [:span @cnt] ", " [myspan2 @cnt]]]])

**Comment by mike-thompson-day8** [comment]
@ZTO  two things:   
  1.  there's just not enough information here for anyone to help you.  Which components?  What arguments changed?  If you ask for help please take the time to distill the problem down and explain it well.  
  2.  This is not the right place to ask this question.  This place is to issues, not asking for help.  

Regarding point 2, please take this up in the various help forums like:
  - http://clojurians.net/ (#reagent channel)
  - https://groups.google.com/forum/#!forum/clojurescript

In the meantime does this page help?  https://github.com/Day8/re-frame/wiki/When-do-components-update%3F

**Comment by ZTO** [comment]
This is a bug report, not asking for help.
I think I distilled it into a minimal, self-explanatory example that demonstrates the issue.
I can also tell you that replacing the splitter component with a regular div solves the update problem, hence my suspicion that the splitter is the culprit.

**Comment by ducky427** [comment]
@ZTO, the behaviour you are experiencing is the way [reagent atoms and components work](https://github.com/Day8/re-frame/wiki/When-do-components-update%3F#a-combination).

**Comment by ZTO** [comment]
@ducky427 are you referring to passing ratoms vs. derefed (and changed) values? If you look at my code, I'm doing the latter, which should trigger a rerender. Again, it does work if I put everything in a basic div, so the problem doesn't seem to be with Reagent or my understanding thereof. It only breaks once I put it in a splitter.

**Comment by mike-thompson-day8** [comment]
Okay, thanks, I see what you mean now.

**Comment by mike-thompson-day8** [comment]
Ahh,  yes, and I can see the bug now.  These were the very first ever components we wrote for re-com  and, sure enough, they have a rookie mistake in them.  

But I'll have to figure out what the right fix is. 

Thanks for reporting it and staying persistent despite my attempts at moving you on . :-)

**Comment by mike-thompson-day8** [comment]
For the record, a fix (incomplete) is simply to change this line:
    https://github.com/Day8/re-com/blob/master/src/re_com/splits.cljs#L122
to ` (fn [& {:keys [panel-1 panel-2]}]`

The current version leaves `panel-1` and `panel-2` as the original parameter value, and never a rerendered value. The proposed change allows new "values" for `panel-1` and `panel-2` to be rendered by the parent. 

But that still leaves the question:  are these the only two parameters which can change?  What about `width` or `style`.   Some thought required.

**Comment by Gregg8** [comment]
@mike-thompson-day8, your suggestion above did indeed fixed the component. This will be included in the next alpha release
