### ISSUE TITLE
Upon code modification Figwheel cannot reload app

### ISSUE THREAD

**Issue by pbudzik** [Day8/re-com#60]
If I refresh manually it works, but it cannot reload itself giving me some bizare error:

utils.cljs:39 Figwheel: notified of file changes
jsloader.js:193 GET http://localhost:3000/legion/core.js?zx=at9wgomycdt8 jsloader.js:193 goog.net.jsloader.loadfile_reloading.cljs:98 (anonymous function)core.cljs:9612 cljs.core.MultiFn.call.G__9144__3core.cljs:9721 cljs.core.MultiFn.call.G__9144file_reloading.cljs:104 figwheel.client.file_reloading.reload_file_STAR_.cljs$core$IFn$_invoke$arity$2file_reloading.cljs:103 figwheel$client$file_reloading$reload_file_STAR_file_reloading.cljs:112 figwheel$client$file_reloading$reload_filefile_reloading.cljs:140 figwheel$client$file_reloading$js_reloadfile_reloading.cljs:147 (anonymous function)
utils.cljs:40 Figwheel: Error loading file legion/core.jsutils.cljs:40 (anonymous function)utils.cljs:42 figwheel.client.utils.log.cljs$core$IFn$_invoke$arity$2utils.cljs:34 figwheel$client$utils$logfile_reloading.cljs:119 (anonymous function)core.cljs:3433 cljs.core.apply.cljs$core$IFn$_invoke$arity$2core.cljs:3424 cljs$core$applyfile_reloading.cljs:101 (anonymous function)deferred.js:649 goog.async.Deferred.fire_deferred.js:298 goog.async.Deferred.updateResult_deferred.js:339 goog.async.Deferred.errbackjsloader.js:179 script.onerror
utils.cljs:39 Figwheel: NOT loading these files

**Comment by mike-thompson-day8** [comment]
You started the process with `lein debug`  ?

**Comment by pbudzik** [comment]
Yes. Didn't help. I figured out that the reason was I had bumped up CLSJ version to org.clojure/clojurescript "1.7.122, falling back to 1.7.107 works, so it was not recom's fault at all.
