### ISSUE TITLE
Togglable tabs

### ISSUE THREAD

**Issue by ducky427** [Day8/re-com#65]
I've got a working version of Bootstrap's [Togglable tabs](http://getbootstrap.com/javascript/#tabs) working with re-com tabs by piggiebacking on the animation effects in bootstrap css file.

Example is [here](https://ducky427.github.io/recom-tabs) and the rough cut of code is [here](https://github.com/ducky427/recom-tabs/blob/master/src/test_tabs/core.cljs).

I wonder if this change would be welcome back in this library. The big change is that instead of displaying only the contents of the selected tab, all the tabs exist in the DOM with only selected tab's contents being visible.

My work can easily live outside this library. But I thought other people may benefit from it.

Happy to work on it to get it in a shape where it can be accepted.

**Comment by Frozenlock** [comment]
The disadvantage I see with this is that things can be become expensive to compute quite fast. You are rendering everything, not just what the user is seeing. In addition, if you change some ratoms associated with hidden tabs, everything will be re-rendered. :cry: 

If you want animations, wouldn't it be better to use React [lifecycle](https://facebook.github.io/react/docs/component-specs.html#lifecycle-methods) handles like `:component-will-unmount`?

**Comment by ducky427** [comment]
@Frozenlock, I think you bring up a great point.

Depending on how the hallowed `reagent/atom` is structured, any change in one tab may or maynot trigger (invisible) updates for another tab. I tend to structure my `app-state` as:

```clojure
{...
    tab-1 {...}
    tab-2 {...}
...}
```

So the effects in one tab don't have any effects on another tab as data is compartmentalised.

This has the advantage that the swtiching tabs is really smooth as from a DOM perspective only a very few things are changing. 

Ofcourse either way there will be a big browser repaint.

So I think with the current strategy and the proposed strategy, there are suboptimal solutions.

But, if adding and removing the classes is moved down to an individual tab component using `:component-will-unmount` and `:component-did-mount`, it may be possible be achieve the same effect without re-com deciding how how many tabs are laid out. It may be possible to achieve either.

I am going to modify my code to see how it functions.

![FTW](http://i0.kym-cdn.com/photos/images/newsfeed/000/538/731/0fc.gif)

**Comment by ducky427** [comment]
I've improved the code so that now you can choose to show all the tabs or not. The code is now in `tab-all` branch.

The example has been updated as well. You may need to clear your browser cache to display the latest version.

In the example, the text above the line is based on all tabs being present. Below the line, the component changes on tab change.

With this new change, the code is a lot simpler and smaller. Nothing will be changed in `re-com` rather a `Tab` component will be added.

**Comment by ducky427** [comment]
Update: I've learnt enough css to realise that this is possible to do this in pure css without changing anything in this library.

**Comment by Gregg8** [comment]
Good to hear you've solved this (re-com repo has not been receiving much love of late due to commercial realities taking precedence). Indeed CSS is a dark art, capable of many things that most are blissfully unaware of, including, no doubt, me.

**Comment by ducky427** [comment]
no worries @Gregg8. But I am a big fan of the work you guys have done here along with re-frame.
