### ISSUE TITLE
IE11 - Modal Issue

### ISSUE THREAD

**Issue by brandonparsons** [Day8/re-com#66]
Hi there,

I know this library is only tested against Chrome, but figured you might want to be made aware of the behavior in other browsers.  I'm typically a Chrome/Safari user, but had a chance to poke around with `re-com` using IE11.

Most of the functionality appears to work reasonably well at first glance, however the basic functionality of modals & tours seem to be broken.

Screenshots FYI:

![ie_modal](https://cloud.githubusercontent.com/assets/1277162/10404800/27c8e4b6-6e92-11e5-8bd8-797e7112b4e8.PNG)

![ie_tour](https://cloud.githubusercontent.com/assets/1277162/10404802/298c1868-6e92-11e5-93b5-b0194ed5b516.PNG)

Feel free to close this issue if you have no intention of fixing these errors for IE. :)

**Comment by mike-thompson-day8** [comment]
Happy to take PR to fix issues on all modern browsers.  But tracking down these sorts of issues is not a priority for us.
