### ISSUE TITLE
Can't turn an h-box into a footer

### ISSUE THREAD

**Issue by chrismurrph** [Day8/re-com#69]
See this SO question:

http://stackoverflow.com/questions/33152382/create-a-footer-using-re-com-box-layout-containers

`:align-self :end` is being ignored

**Comment by mike-thompson-day8** [comment]
Answered on stackoverflow (I think).  

As a general rule I don't look at SO much.  There are other support forms where you'll probably get an answer sooner:  https://github.com/Day8/re-frame/blob/master/CONTRIBUTING.md#support-questions
