### ISSUE TITLE
label only works with strings and not hiccup syntax

### ISSUE THREAD

**Issue by ducky427** [Day8/re-com#7]
On Line 39 of [text.clj](https://github.com/Day8/re-com/blob/master/src/re_com/text.cljs#L39), `str` function is applied to `label` which I am guessing isn't the intended behaviour.

Fix would be to not apply the `str` function.

Thanks

**Comment by Gregg8** [comment]
Sorry, we've had big storms here and my Internet has been down.

The idea of the [label] was to have a small component for short strings, such as labels for form fields.

To do more complex stuff, you could use a [box] which is a generic container, equivalent to a [:div] in html but wrapped with goodies to make it play well in this re-com/flexbox world.

Having said all that, I realise the description of [label] actually says it should accept hiccup or anything so yes, I WILL remove the (str) for the next release.

The other good reason for doing this is that [label] is actually an "inline" component, more similar to an html [:span], in contrast to the "block-level" [box].

Thanks for pointing this out.

**Comment by ducky427** [comment]
Thanks!

**Comment by Gregg8** [comment]
Fixedd in release 0.5.3 - [click here](https://github.com/Day8/re-com/releases/tag/0.5.3) for more deails.

**Comment by ducky427** [comment]
Thanks a lot!
