### ISSUE TITLE
tooltips showing? state can become stale when target is disabled

### ISSUE THREAD

**Issue by scgilardi** [Day8/re-com#70]
In several cases in `re-com.buttons`, an internal atom called `showing?` keeps track of whether or not a tool tip is showing on a host component. The atom's state is changed only by handling `on-mouse-over` and `on-mouse-out` events.

When a button becomes disabled, it no longer receives `on-mouse-over` or `on-mouse-out` events. The state of `showing?` at the time the button is disabled becomes "stuck" at whatever value it has. If pressing a button causes the pressed button to become disabled (e.g., a "delete the selected items" button), the tooltip gets stuck showing on screen.

I have a fix for this that works for me. I'm happy to make a pull request for this and the other cases in `re-com.buttons`, but I don't see any good way to write a unit test for it.

Here's an example of the suggested addition:

```diff
index d0a0a6c..656940e 100644
--- a/src/re_com/buttons.cljs
+++ b/src/re_com/buttons.cljs
@@ -44,10 +44,12 @@
                           (when tooltip
                             {:on-mouse-over (handler-fn (reset! showing? true))
                              :on-mouse-out  (handler-fn (reset! showing? false))})
                           attr)
                         label]]
+        (when disabled?
+          (reset! showing? false))
         [box
          :class "display-inline-flex"
          :align :start
          :child (if tooltip
                   [popover-tooltip
```

**Comment by scgilardi** [comment]
This allows a simplification of the button demo:

```diff
index 1027540..9e6391e 100644
--- a/src/re_demo/button.cljs
+++ b/src/re_demo/button.cljs
@@ -52,7 +52,7 @@
                                           [h-box
                                            :children [[button
                                                        :label            "No Clicking!"
-                                                       :tooltip          (when-not (= (:outcome-index @state) (dec (count click-outcomes))) "Seriously, NO CLICKING!")
+                                                       :tooltip          "Seriously, NO CLICKING!"
                                                        :tooltip-position :below-center
                                                        :disabled?         (= (:outcome-index @state) (dec (count click-outcomes)))
                                                        :on-click          #(swap! state update-in [:outcome-index] inc)```

**Comment by Gregg8** [comment]
Thanks for pointing this out. Would be happy to receive a PR for this fix. Regarding tests, you'll see that the re-com library is not test-heavy so just providing the code would be appreciated.

**Comment by scgilardi** [comment]
Thanks. Closing this issue in favor of the pull request: https://github.com/Day8/re-com/pull/71 .
