### ISSUE TITLE
Can't get datepicker or datepicker-dropdown to work

### ISSUE THREAD

**Issue by tuhlmann** [Day8/re-com#73]
Hey, and I'm sorry if that is a stupid question.
I'm banging my head over this for far too long and figured I would ask for help.

So, I'm trying to add a datepicker-dropdown (or datepicker) to my app (using latest re_com), but that fails with an error thrown in `unparse`:

```
ERROR unparse  TypeError: Cannot read property 'call' of null
```

I tried to add a datepicker like this:

```
[datepicker
  :model invoice-date
  :on-change #("New Date " (pr-str %))]
```

`invoice-date` is `(r/atom (minus (now) (days 3)))`

The problems seems to happen when a formatter is search in `formatter-fn` (in cljs-time):

`((or formatter-overrides formatters) %)` this seems to return nil. The value passed into that anonymous fn seems to be:

```
["MMMM" "MMMM" nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil]
```

I can't really figure out what the problem is, I'm sure its some tiny little detail somewhere.

Does it make a difference that my browser's locale is german?

Thanks,
Torsten.

PS: The documentation says `:model` is optional however if I omit it I run into a deref error.

**Comment by mike-thompson-day8** [comment]
Does the demo app work okay for you?  If so, then it won't be related to the locale. 

I'd start by nudging the demo around so it mimics what you have in your code.

**Comment by tuhlmann** [comment]
@mike-thompson-day8 The demo app works beautifully for me- no errors in the console and the datepicker shows up nicely.

Thanks for looking at it!

**Comment by tuhlmann** [comment]
I copied all my project's dependencies into re-com's project.clj and now the demo exhibits the same problem. I'll let you know when I figure out the exact dependency causing this.

**Comment by tuhlmann** [comment]
@mike-thompson-day8 Got it!
I was using `[org.clojure/clojurescript "1.7.145"]` in my project, that caused the problem,
As soon as I change the version you use to this one (keeping all my other dependencies) that problem appears in your app.

I did update cljs-time to "0.3.13" and the problem disappeared. The deps on your project are now:

```
:dependencies    
                [[org.clojure/clojure "1.7.0"]
                 [reagent "0.5.1"]
                 [org.clojure/clojurescript "1.7.145"]
                 [com.andrewmcveigh/cljs-time "0.3.13"]]
```

Would it be ok for you to update these dependencies?

**Comment by mike-thompson-day8** [comment]
In summary:  if you use `[org.clojure/clojurescript "1.7.145"]`  then use `[com.andrewmcveigh/cljs-time "0.3.13"]`

If you provide those deps in your app's `project.clj`, they will override the ones in re-com. So you don't need to wait for a new re-com release.  
 
Having said that, we'll be doing a new release shortly (within a week or so) and we will include these new dependencies for the demo app.

**Comment by tuhlmann** [comment]
Thank you, I got it working!

I had this setup before and it still failed, even after a `lein clean`.

Then I moved the `cljs-time` dependency below `re-com` and it started working. I moved it back at the previous position and it continued to work, even after clean. 

Thanks for your help,
Torsten.
