### ISSUE TITLE
Auto border UI components when in dev

### ISSUE THREAD

**Issue by arichiardi** [day8/re-com#74]
I actually found this very useful hack in Android.

You can add a border to your UI components/containers so that they show their size/position.

In `re-com` you already have the `border` border component and it would be great to wrap each and every other UI element in a in when in dev mode.

Another maybe simpler idea is to have a `with-border` macro that wraps when you need it. This last idea is almost already in place here :+1: 

Great tool by the way, even if flexbox sometimes makes me crazy.

**Comment by mike-thompson-day8** [comment]
There is a more limited capability already there which will draw a border around the vbox and hbox. 

Try this: 
`(set! re-com.box/debug true)`

**Comment by arichiardi** [comment]
Cool stuff, exactly what I need it :+1:

**Comment by mike-thompson-day8** [comment]
We need to add some docs around this.

**Comment by arichiardi** [comment]
:+1:

**Comment by Gregg8** [comment]
Might review the colours at the same time. Just had another look at it. Was only put in while making the box module, but glad others might find it useful. Will document it for the next release.

**Comment by arichiardi** [comment]
Thanks! In Android the color is red, but I also find useful to differentiate (random among say 15?). A macro would have been the best as you can "pass through" your object, prepending it..kind of like `trace` for clojure functions, which prints and returns the unmodified result of the function up the call stack.

**Comment by Gregg8** [comment]
You said you your macro was "almost in place", so feel free to pass it along when you're happy with it :-)

**Comment by arichiardi** [comment]
True :smile: I will! No ETA though as I am a bit swamped..

**Comment by mike-thompson-day8** [comment]
This issue is rather old, so I'm going to close. 
I have recently added a note in the documentation regarding `(set! re-com.box/debug true)`
