### ISSUE TITLE
Popover content when <pre> <code> is not very nice

### ISSUE THREAD

**Issue by arichiardi** [Day8/re-com#75]
I know I know it is always a matter of taste, but I felt that adding

```
.popover-content code {
  color: inherit;
  background-color: inherit;
  border: none;
}
```

Improved a bit this:

![selection_027](https://cloud.githubusercontent.com/assets/1724788/11131130/da66f174-893d-11e5-8327-434e78f54826.png)

Feel free to dismiss and close this at will :smile:

**Comment by Gregg8** [comment]
Unfortunately this CSS breaks some of our other popovers, specifically the `popover-tooltip` in `:info` mode.

Current (from our [h-box demo](http://localhost:3449/index_dev.html#/h-box) page):
![image](https://cloud.githubusercontent.com/assets/3037372/18571000/3ff338f2-7bf2-11e6-9678-92159d6f324e.png)

With CSS change:
![image](https://cloud.githubusercontent.com/assets/3037372/18580014/6be5843e-7c3c-11e6-922d-68e8f4d1a17d.png)

So we'll leave it as is for now and allow it to be overridden as required.

**Comment by Gregg8** [comment]
Closing. Please reopen if required.
