### ISSUE TITLE
scrollable component will scroll to top if autofocus attribute set on input-text

### ISSUE THREAD

**Issue by benhowell** [Day8/re-com#82]
I have a number of popovers with input-text components which contain "auto-focus" attribute inside a scrollable v-box.
When a popover is activated and autofocus fires, the v-box scrolls back to top. If I remove auto-focus the problem goes away.

I've attached a screenshot which may make my explanation a little clearer.

Here's the offending code:
```clojurescript
[re-com/input-text
 :width "180px"
 :height "32px"
 :style {:font-size "14px"}
 :model text-val
 :on-change #(reset! text-val %)
 :attr {:auto-focus "autofocus"
        :on-click (handler-fn
                   (.preventDefault event)
                   (.stopPropagation event))}
 :placeholder placeholder]
```

![snapshot1](https://cloud.githubusercontent.com/assets/1784519/12345415/ae725946-bb9c-11e5-80f9-b24739dd7a29.png)

**Comment by Gregg8** [comment]
I was not able to reproduce this, so could you please provide more information. Perhaps a gist?

btw, we normally use `{:auto-focus true}`.

**Comment by benhowell** [comment]
Hi,
Unfortunately I've since moved away from re-com and don't have the original code on hand from 8 months ago. Seeing no one else has commented in that time and you weren't able to reproduce it, it's probably safe to close this issue. Thanks!

**Comment by Gregg8** [comment]
ok, thanks.
