### ISSUE TITLE
Allow button label to be passed in to alert box. [re-com "0.8.0"]

### ISSUE THREAD

**Issue by benhowell** [Day8/re-com#85]
For those not using material design icons, the :closeable? arg on alert-box does not work as it's hard coded as a material design icon. Allowing the button label or button itself to be passed in would be nice.

https://github.com/Day8/re-com/blob/master/src/re_com/alert.cljs#L32

**Comment by Gregg8** [comment]
Material design icons are used all over the place in re-com, so this would not be a small change to do it properly. If it'is really important for this to be included, then could you please submit a PR.

**Comment by benhowell** [comment]
No, that's fine. I'll close the issue. Thanks!

**Comment by Gregg8** [comment]
As per #82, you say you no longer use re-com so I will close this one as well.

**Comment by Gregg8** [comment]
(lol, had not updated my github page)
