### ISSUE TITLE
Note about api namespace in docs

### ISSUE THREAD

**Issue by metasoarous** [Day8/re-com#86]
I can't find anywhere in the docs or the re-com demo introduction anywhere that the api namespace is `re-com.core`. I know it's easy enough to figure out by looking at the repo, but that's one of the first things I usually look after the clojars coords, so it would be nice if it was visible :-)

**Comment by Gregg8** [comment]
Do you have a suggestion for where this information should live? And how much detail would you expect to see? Link to any examples?

**Comment by metasoarous** [comment]
A short section near the top of the introduction page would suffice. Something like:

## Getting started

First add the coordinates `[re-com "0.9.0"]` to your `project.clj` dependencies. You should now be able to require the `re-com.core` namespace, which exposes all of the API functions documented in this example app.

**Comment by Gregg8** [comment]
OK, this has been added and will appear in the next release, which should be ready in a short while.
