### ISSUE TITLE
Allow user to select the datepicker dropdown position

### ISSUE THREAD

**Issue by Frozenlock** [day8/re-com#87]
It seems the dropdown position is hardcoded to `:below-left`.
(See https://github.com/Day8/re-com/blob/master/src/re_com/datepicker.cljs#L252)

The problem I have with this is that if I want this datepicker to be on the left of the screen, the dropdown overflows outside the window.

Would it be possible to let the user select the position?

**Comment by Gregg8** [comment]
We would be happy to take a PR on this one.

**Comment by MawiraIke** [comment]
I have made a fix for this that adds the keyword argument `position` to the `datepicker-dropdown` component. The `position` keyword can be any `position` supported in the `popover` component.
Attaching it below.
