### ISSUE TITLE
datepicker doesn't switch month panel when updating model

### ISSUE THREAD

**Issue by pbaille** [Day8/re-com#97]
When i swap! the model of a datepicker to a Date not in the current month, the UI remain on the same month I have to switch month manually to retreive the selection.

**Comment by Frozenlock** [comment]
I just noticed the same thing.
I wanted to use the datepicker to show a given date, but the visible month does not update when the model atom is updated.

As an aside, I also noticed that adding `:disabled? true` will not remove deactivate the month-selection arrows.

**Comment by Frozenlock** [comment]
Here's the "bug" in action : 

![calendar-not-showing-current-date](https://cloud.githubusercontent.com/assets/1152041/18819907/808889a0-8366-11e6-811e-22bfd7294f89.gif)

(I know @Gregg8 already referenced this issue, but I just wanted to make it clear.)
