### ISSUE TITLE
Button is impervious to attempts to style/align it...

### ISSUE THREAD

**Issue by johanatan** [day8/re-com#99]
... due to it having been embedded within a 'box' whose styles are untouchable by user code. e.g., try setting "padding-left: 5em" on a button and notice that the text inside is padded but the button itself occupies the entire padded space. Another example: try setting "align-self: flex-end" and notice that it doesn't have any effect at all.

**Comment by arichiardi** [comment]
Yep, I think this issue is the same as this: https://github.com/Day8/re-com/issues/76

**Comment by johanatan** [comment]
Yes, looks the same to me as well.

**Comment by superstructor** [comment]
As of `2.12.0` this should be solved by use of the new `:parts` arg and the `:wrapper` part keyword; see https://re-com.day8.com.au/#/button 'Parts' section.
